#!/usr/bin/env python3
"""Regenerate the live record-count tables in README.md.

Counts the real, served line totals from ``data/full-*.txt`` (i.e. what a
firewall actually pulls, after allowlist/bogon filtering) and rewrites the
content between the ``STATS-TR`` / ``STATS-EN`` marker comments. Run by the
GitHub Actions workflow before each commit so the README always reflects the
lists that ship alongside it.
"""
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = Path("data")
README = ROOT / "README.md"
STATE_FILE = DATA_DIR / "_state.json"

# Time windows (in days) shown as columns; "full" is the all-time list.
WINDOWS = [30, 60, 90, 120]

# (emoji, TR label, EN label, filename stem) — files are days-<w>-<stem>.txt / full-<stem>.txt
TYPES = [
    ("🌐", "Domain", "Domain", "domains"),
    ("🔗", "URL", "URL", "urls"),
    ("📡", "IPv4", "IPv4", "ips"),
    ("🧭", "IPv6", "IPv6", "ip6"),
    ("🕸️", "IPv6 Ağ", "IPv6 Net", "ip6net"),
]


def count_lines(path: Path) -> int:
    """Number of non-empty lines in *path* (0 if it does not exist)."""
    if not path.exists():
        return 0
    with path.open("r", encoding="utf-8") as fh:
        return sum(1 for line in fh if line.strip())


def last_updated() -> str:
    """Human-readable timestamp from _state.json (UTC+3), or today's date."""
    try:
        state = json.loads(STATE_FILE.read_text(encoding="utf-8"))
        ts = state.get("last_run") or state.get("last_full_completed")
        if ts:
            return datetime.fromisoformat(ts).strftime("%Y-%m-%d %H:%M")
    except (OSError, ValueError, json.JSONDecodeError):
        pass
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def build_table(matrix: dict[str, list[int]], lang: str) -> str:
    """Render the window-by-type count matrix for a language ('tr' or 'en').

    *matrix* maps each type stem to a row of counts, one per window plus full.
    """
    sep = "." if lang == "tr" else ","

    def fmt(n: int) -> str:
        return f"{n:,}".replace(",", sep)

    cols = [f"{w}g" if lang == "tr" else f"{w}d" for w in WINDOWS] + ["Full"]
    type_head = "Tip" if lang == "tr" else "Type"
    total_label = "Toplam" if lang == "tr" else "Total"
    if lang == "tr":
        stamp = f"_Son güncelleme: {last_updated()} (UTC+3) — bot tarafından otomatik._"
    else:
        stamp = f"_Last updated: {last_updated()} (UTC+3) — auto-generated by the bot._"

    header = f"| {type_head} | " + " | ".join(cols) + " |"
    align = "| --- " + "| --: " * len(cols) + "|"

    rows = []
    for emoji, tr, en, stem in TYPES:
        label = tr if lang == "tr" else en
        cells = " | ".join(fmt(n) for n in matrix[stem])
        rows.append(f"| {emoji} {label} | {cells} |")

    totals = [sum(matrix[stem][i] for stem in matrix) for i in range(len(cols))]
    rows.append(f"| **{total_label}** | " + " | ".join(f"**{fmt(n)}**" for n in totals) + " |")

    return "\n".join([header, align, *rows, "", stamp])


def replace_block(text: str, marker: str, body: str) -> str:
    start = f"<!-- {marker}:START -->"
    end = f"<!-- {marker}:END -->"
    pattern = re.compile(
        re.escape(start) + r".*?" + re.escape(end),
        re.DOTALL,
    )
    if not pattern.search(text):
        raise SystemExit(f"Marker block '{marker}' not found in README.md")
    return pattern.sub(f"{start}\n{body}\n{end}", text)


def main() -> None:
    matrix = {}
    for _, _, _, stem in TYPES:
        row = [count_lines(DATA_DIR / f"days-{w}-{stem}.txt") for w in WINDOWS]
        row.append(count_lines(DATA_DIR / f"full-{stem}.txt"))
        matrix[stem] = row
    text = README.read_text(encoding="utf-8")
    text = replace_block(text, "STATS-TR", build_table(matrix, "tr"))
    text = replace_block(text, "STATS-EN", build_table(matrix, "en"))
    README.write_text(text, encoding="utf-8")
    print("README counts updated:", {k: v[-1] for k, v in matrix.items()})


if __name__ == "__main__":
    main()
